language: java
dist: trusty
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: braindead-dev-github
    branches:
      - masterClient
      - masterServer


notifications:
    email: false

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar