INSERT into Building (BUILDING_ID, name) VALUES (1, 'Oil Refinery');
INSERT into Building (BUILDING_ID, name) VALUES (2, 'Iron Mine');
INSERT into Building (BUILDING_ID, name) VALUES (3, 'Forestry');
INSERT into Building (BUILDING_ID, name) VALUES (4, 'Headquarters');
INSERT into Building (BUILDING_ID, name) VALUES (5, 'Warehouse');
INSERT into Building (BUILDING_ID, name) VALUES (6, 'Barracks');
INSERT into Building (BUILDING_ID, name) VALUES (7, 'Training grounds');
INSERT into Building (BUILDING_ID, name) VALUES (8, 'Foundry');
INSERT into Building (BUILDING_ID, name) VALUES (9, 'Ammunition Depot');
INSERT into Building (BUILDING_ID, name) VALUES (10, 'Wall');